# logging.yaml

version: 1
disable_existing_loggers: False

formatters:
  default:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  file_handler:
    class: logging.FileHandler
    level: INFO
    formatter: default
    filename: logs/app.log
    encoding: utf8

  console_handler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default

loggers:
 :
    level: DEBUG
    handlers:
      - file_handler
      - console_handler
    propagate: no

root:
  level: INFO
  handlers:
    - file_handler
    - console_handler
